name: Feature Request
description: Suggest a new feature or enhancement for the platform
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please fill out the form below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Frontend (React)
        - Backend (Django)
        - API
        - Database
        - Authentication
        - Code Execution (Judge0)
        - Infrastructure (Docker)
        - Documentation
        - Multiple Components
        - New Component
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Important for functionality
        - Critical - Blocking current work
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Minor change or addition
        - Medium - Moderate development effort
        - Complex - Significant development effort
        - Major - Requires architectural changes
        - Unknown - Not sure about complexity

  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: Describe this feature as a user story
      placeholder: |
        As a [type of user],
        I want [goal/desire]
        So that [benefit/value]

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: What would need to be true for this feature to be considered complete?
      placeholder: |
        - [ ] Feature does X
        - [ ] Feature handles Y scenario
        - [ ] Feature is accessible
        - [ ] Feature is tested

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Design Ideas
      description: Any visual mockups, wireframes, or design ideas
      placeholder: Add links to mockups, wireframes, or describe the UI/UX

  - type: textarea
    id: api_changes
    attributes:
      label: API Changes
      description: Would this feature require API changes? If so, describe them.
      placeholder: |
        New endpoints:
        - POST /api/new-feature/
        
        Modified endpoints:
        - GET /api/existing-endpoint/ (add new field)

  - type: textarea
    id: technical_considerations
    attributes:
      label: Technical Considerations
      description: Any technical considerations or constraints
      placeholder: |
        - Performance implications
        - Security considerations
        - Database changes needed
        - Third-party integrations

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Examples of similar features in other platforms
      placeholder: Links to similar features in other coding platforms or applications

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context or information about the feature request.
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to implementing this feature?
      options:
        - label: I would like to work on this feature
        - label: I can help with design/planning
        - label: I can help with testing
        - label: I can help with documentation

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched for similar feature requests
          required: true
        - label: I have provided a clear description of the feature
          required: true
        - label: I have explained the value this feature would provide
          required: true