# Override to use Apache instead of Nginx for the web service.
# Usage:
#   docker compose -f infra/compose/prod/docker-compose.yml -f infra/compose/prod/docker-compose.apache.yml up -d --build
# The original 'web' service definition is replaced to build with Apache.

services:
  web:
    build:
      context: ../../..
      dockerfile: infra/docker/apache/Dockerfile.prod
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    # Keep ports/volumes identical to nginx variant
    ports:
      - "80:80"
    volumes:
      - static_data:/var/www/static:ro
      - media_data:/var/www/media:ro
    depends_on:
      - backend
    restart: unless-stopped
