# Generated by Django 5.0.6 on 2025-09-08 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_passwordresettoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PasswordResetToken",
        ),
    ]
