# Generated by Django 5.2.5 on 2025-09-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_submission_models"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="problem",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="submissiontestcaseresult",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="usersolution",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="student",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("RUNNING", "Running"),
                    ("DONE", "Done"),
                    ("ERROR", "Error"),
                ],
                default="QUEUED",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="problem",
            constraint=models.UniqueConstraint(
                fields=("contest", "code"), name="uniq_problem_contest_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="submissiontestcaseresult",
            constraint=models.UniqueConstraint(
                fields=("submission", "index"), name="uniq_result_submission_index"
            ),
        ),
        migrations.AddConstraint(
            model_name="usersolution",
            constraint=models.UniqueConstraint(
                fields=("student", "problem"), name="uniq_solution_student_problem"
            ),
        ),
    ]
