# Generated by Django 5.2.6 on 2025-09-12 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_function_stub_fields"),
        ("accounts", "0006_constraints_update"),
    ]

    operations = []
