# Generated by Django 5.2.5 on 2025-09-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_contest_attempt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contestattempt',
            new_name='accounts_co_student_e76ea8_idx',
            old_name='accounts_co_student_0ee304_idx',
        ),
        migrations.AlterField(
            model_name='contestattempt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
