# Generated by Django 5.2.5 on 2025-09-14 14:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_accounts_co_student_0ee304_idx_accounts_co_student_e76ea8_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuniorSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orig_submission', models.UUIDField()),
                ('code', models.TextField()),
                ('language', models.CharField(default='python', max_length=20)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('ERROR', 'Error')], default='QUEUED', max_length=10)),
                ('score', models.FloatField(default=0)),
                ('max_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judge0_tokens', models.JSONField(blank=True, default=list)),
                ('judge0_raw', models.JSONField(blank=True, default=dict)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junior_submissions', to='accounts.problem')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='junior_submissions', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='SeniorSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orig_submission', models.UUIDField()),
                ('code', models.TextField()),
                ('language', models.CharField(default='python', max_length=20)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('ERROR', 'Error')], default='QUEUED', max_length=10)),
                ('score', models.FloatField(default=0)),
                ('max_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judge0_tokens', models.JSONField(blank=True, default=list)),
                ('judge0_raw', models.JSONField(blank=True, default=dict)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senior_submissions', to='accounts.problem')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='senior_submissions', to='accounts.student')),
            ],
        ),
    ]
