# Generated by Django 5.0.6 on 2025-09-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_practicecategory_practicequestion_practiceoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicequestion',
            name='solution',
            field=models.TextField(blank=True, help_text='Detailed step-by-step solution (optional)'),
        ),
        migrations.AlterField(
            model_name='practicequestion',
            name='explanation',
            field=models.TextField(blank=True, help_text='Short explanation or justification'),
        ),
    ]
