FROM node:20-alpine AS build-frontend
WORKDIR /app/frontend
COPY frontend/package*.json ./
RUN npm ci || npm install
COPY frontend/ /app/frontend/
ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
RUN npm run build

FROM nginx:alpine
RUN mkdir -p /var/www/static /var/www/media
COPY infra/docker/nginx/prod.conf /etc/nginx/conf.d/default.conf
COPY --from=build-frontend /app/frontend/dist/ /usr/share/nginx/html/
VOLUME ["/var/www/static", "/var/www/media"]
EXPOSE 80