name: CI

on:
  pull_request:
    branches: [ main, master ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r backend/requirements/dev.txt

      - name: Black (check)
        run: |
          python -m black --check src/

      - name: Ruff (lint)
        run: |
          python -m ruff check src/

      - name: Pytest
        env:
          DJANGO_SETTINGS_MODULE: student_auth.settings
          PYTHONPATH: src/student_auth
          USE_SQLITE: '1'
        run: |
          python -m pytest -q

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      - name: Prettier (check)
        working-directory: frontend
        run: npm run format:check

      - name: ESLint
        working-directory: frontend
        run: npm run lint

      - name: Frontend tests
        working-directory: frontend
        run: npm test --silent --if-present
